# Generated by Django 2.2.3 on 2019-07-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20190720_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='deadline',
            field=models.DateField(null=True, verbose_name='締め切り(任意)'),
        ),
    ]
